package dsl.model;

public enum MessageType {
    REQUEST, RESPONSE,
    VOTE_REQUEST, VOTE_RESPONSE,
    APPEND_ENTRIES, HEARTBEAT,
    REPLICATION, COMMIT, ABORT,
    PING, PONG, DISCOVERY, ELECTION, SYNC,
    PREPARE, OK, COORDINATOR, LOOKUP
}